### ISSUE TITLE
Catalog is showing `observers` array as part of public api :(

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer-element-catalog#210] opened 2015-11-04 01:52 UTC
Not sure if this is due to a recent deployment.

<img width="538" alt="screen shot 2015-11-03 at 5 50 22 pm" src="https://cloud.githubusercontent.com/assets/238208/10927304/7ee8ee60-8253-11e5-93a8-000a3df8efbd.png">

**Comment by blasten** [comment] 2015-11-04 18:38
@garlicnation I found that hydrolysis doesn't set `configuration:true` there. Would you mind taking a look?

**Comment by garlicnation** [comment] 2015-11-05 19:39
The problem is that I'm not special-casing `observers` in a behavior. I can fix it in the next couple of days.

**Comment by blasten** [comment] 2015-11-17 02:42
friendly ping @garlicnation

**Comment by garlicnation** [comment] 2015-11-17 17:42
Should be resolved by https://github.com/Polymer/hydrolysis/pull/197

**Closed** 2015-11-17 19:08 UTC
