### ISSUE TITLE
Scrolling is broken in Safari

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer-element-catalog#203] opened 2015-10-24 08:27 UTC
Scrolling doesn't work on Safari on demos that require scrolling(https://elements.polymer-project.org/elements/paper-card?view=demo:demo/index.html&active=paper-card, https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input)

**Comment by frankiefu** [comment] 2015-10-27 01:13
This is an issue in `iron-component-page` and seems to be a regression from https://github.com/PolymerElements/iron-component-page/commit/92dc7c796828bfd792f355e00fd1a74de2f532d4.  I can see the double scrollbars when view the paper-input's demo but the double scrollbars is more fatal in Safari.

<img width="949" alt="screen shot 2015-10-26 at 6 11 10 pm" src="https://cloud.githubusercontent.com/assets/116360/10746981/3ab775fa-7c0d-11e5-8d46-90a9ef883b88.png">

**Comment by blasten** [comment] 2015-11-03 22:54
This issue should be fixed now.

**Closed by blasten** 2015-11-03 22:54 UTC
