### ISSUE TITLE
Link to currently visible element documentation should be visible in the sidebar

### ISSUE THREAD

**Issue by Ajedi32** [Polymer/polymer-element-catalog#98] opened 2015-06-02 19:33 UTC
Minor annoyance I noticed while browsing the catalog. When you're viewing the documentation for an element, the link to that element in the sidebar disappears, instead of being visible and highlighted as the "current page", as is the case with (for example) the doc and demo nav items:

![paper material polymer element catalog](https://cloud.githubusercontent.com/assets/1876931/7944962/758b13b4-0933-11e5-8d31-5dc301b2c920.png)

This is particularly annoying when you want to look through the docs for all the different elements sequentially, as the highlighted element would normally serve as a placeholder in the list, making it easy to see visually which element is "next" in the list. The absence of this placeholder is a bit confusing and makes that workflow more difficult.

**Comment by Ajedi32** [comment] 2015-06-02 19:34
I noticed the elements in that nav area are labeled "**Other** Paper Elements", so maybe this was intentional? Still pretty annoying, in my opinion at least.

**Comment by mbleigh** [comment] 2015-06-02 20:02
Duplicate of #56 -- yeah it was a bad design call on my part. Going to fix.

**Closed by mbleigh** 2015-06-02 20:02 UTC
