### ISSUE TITLE
Search button on home page doesn't work

### ISSUE THREAD

**Issue by garlicnation** [Polymer/polymer-element-catalog#93] opened 2015-06-01 21:07 UTC
Search from individual elements works, but clicking the magnifying glass on the first page shows me nothing(in chrome beta on mac)

**Comment by addyosmani** [comment] 2015-06-01 21:11
Confirmed. Oddly doesn't work in Chrome but does in Safari.

**Comment by Ajedi32** [comment] 2015-06-02 19:01
Works for me. Is this fixed now? https://elements.polymer-project.org/

**Comment by tjsavage** [comment] 2015-06-02 19:16
Seeing the same behavior for me, 43.0.2357.81 on mac

**Comment by Ajedi32** [comment] 2015-06-02 19:20
Okay, this is weird. I *know* this was working for me a second ago, but now it's not anymore. I have no idea... oh wait.

Okay, so it seems the search feature is broken *until* you navigate to the main catalog (by clicking on one of the element categories) then click the polymer logo to go back to the home page. After that, the search works as expected.

**Comment by drewp** [comment] 2015-06-04 04:56
Broken on Chrome Version 44.0.2391.0 dev, ubuntu

**Comment by ebidel** [comment] 2015-06-08 01:06
Seeing this too and can confirm the search icon works once you navigate away from the homepage and back to it.

**Closed** 2015-06-11 21:05 UTC
Labels: p1
